# Generated by Django 5.0.6 on 2024-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_item_options_claim_is_approved_item_reporter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_found",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
